image: node:6

before_script:
  - ping -c 1 aksw.org

build_the_project:
  script:
#    - sh program.sh
    - test -f result.md

release-job:
  before_script:
    - npm install -g markdown-pdf
  script:
    - markdown-pdf Webseiten/docu.md
    - mv Webseiten/docu.pdf docu.pdf
  artifacts:
    paths:
    - result.pdf
    - docu.pdf
  only:
    - tags
